### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Garito** [liftoff/HumanInput#10]
Hi!
Wouldn't be nice to have this library hosted on a CDN?

Thanks!

**Comment by liftoff** [comment]
Yes it would!  I'll see what I can do to get it added.  You can request it be added to various CDNs on your own too (that would be helpful, actually).  Right now I'm trying to do what's necessary to get it added to cdnjs.com...

**Comment by liftoff** [comment]
Actually never mind:  It's already in a CDN (jsdelivr)!  Examples:

* https://cdn.jsdelivr.net/npm/humaninput/dist/humaninput-full.min.js
* https://cdn.jsdelivr.net/npm/humaninput/dist/humaninput-1.1.14-full.min.js

Enjoy =)

**Comment by Garito** [comment]
Thanks!
