### ISSUE TITLE
ctrl-shift sequence

### ISSUE THREAD

**Issue by drschwabe** [liftoff/HumanInput#16]
Hi, I'd like to catch 'ctrl-shift-e ctrl-shift-e'.  Such that the user doesn't need to release ctrl and shift - only needs to hit "e" twice. but can't seem to.   I tried: 

```
//this doesn't catch: 
HI.on('ctrl-shift-e ctrl-shift-e', (event)=>{ ... })

//this catches OK: 
HI.on('ctrl-shift-e e', (event)=>{ ... })
```
the later works but only if you release ctrl-shift what I'd like is to keep ctrl-shift held down. 

What is the better approach?

**Comment by riskable** [comment]
This is an interesting use case but it should be pretty easy to handle if you write a function that attaches to `ctrl-shift-e` and merely checks if it's been called twice.  You can also attach a function to `keyup` (or `keydown`--recommend `keyup` though so you avoid key repeat situations) that resets the state of your handler function.

You can also reference the current state of what's 'down' by calling the `.getDown()` function (e.g. `HI.getDown()`) so you can check if there's any other keys being held down at the moment and deal with that situation however you like.

**Comment by liftoff** [comment]
This is an interesting use case but it should be pretty easy to handle if you write a function that attaches to `ctrl-shift-e` and merely checks if it's been called twice.  You can also attach a function to `keyup` (or `keydown`--recommend `keyup` though so you avoid key repeat situations) that resets the state of your handler function.

You can also reference the current state of what's 'down' by calling the `.getDown()` function (e.g. `HI.getDown()`) so you can check if there's any other keys being held down at the moment and deal with that situation however you like.

**Comment by drschwabe** [comment]
Thanks for the suggested ideas! You're right easy logic to solve it using a counter, nice.
