### ISSUE TITLE
The latest version tag problem

### ISSUE THREAD

**Issue by emmy41124** [liftoff/HumanInput#8]
Hello @liftoff ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I downloaded the latest version from github, and I found the latest version is `v1.1.13`, but the latest release tag is `v1.1.12`. Do you attempt to release the version `v1.1.13`?
![image](https://cloud.githubusercontent.com/assets/17833603/21500659/21d6ad88-cc7c-11e6-92c5-11d81c0e9054.png)

By the way, the version of repository on [npm](https://www.npmjs.com/package/humaninput) is also `v1.1.12`. Could you update the latest version on npm?
Thanks very much!

cdnjs/cdnjs#9837

**Comment by liftoff** [comment]
This issue should now be corrected:  The release now matches the version in the repo and in NPM.
