### ISSUE TITLE
Help with gamepad plugin

### ISSUE THREAD

**Issue by bleasby** [liftoff/HumanInput#9]
First of all thks for the library! It is really nice to have all those different human inputs handled by the same framework!
Altouhg, I must be doing something wrong when trying to use the gamepad plugin.

I downloaded the git files and added this to the head of my html:
`<script src="extjs/humaninput-1.1.13-full.js"></script>`

and them in the end of the body I added this to intialize the gamepad event check:
`
//initialize Human Input
	var settings = {addEvents: ['gamepad']}; 
	var HI = new HumanInput(window, settings);
`

Whenever I run this, the bellow message appears on my console.log every time that the gamepadUpdate() function is called on the loop:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at gamepadUpdate (humaninput-1.1.13-full.js:2831)
```

There is any problem with the gamepad plugin or am I doing something wrong?

**Comment by bleasby** [comment]
More info about the problem.
When initialized the "this" inside the GamepadPlugin.prototype.gamepadUpdate function references to the GamepadPlugin object. However, after each subsequent gamepadUpdate() call, it references to the window object instead. 
The problem is definitely on that but I lack the knowledge about your code to make any necessary change to fix it. 
I would really like to use this library. 
I hope anyone could chime on that.
Anyone has the gamepad HI feature working on last version?

**Comment by liftoff** [comment]
You're right:  It's broken.  I think I've figured out what's going on (recent browser changes in regards to ES6 support).  I'll post a fix soon.

**Comment by liftoff** [comment]
All fixed!  I just pushed a commit and a new version (1.1.15) that should resolve this issue.  Coincidentally I also noticed that when browsers detect axis as buttons HumanInput would think they're "down" and as a result you'd get unnecessary "hold" events.  I fixed that too while I was at it =)
